/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/category` | `/category`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exhibitionLog` | `/exhibitionLog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage` | `/mypage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/liked` | `/mypage/exhibition/liked`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/thumbs-up` | `/mypage/exhibition/thumbs-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/visited` | `/mypage/exhibition/visited`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/category`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/interest`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/exhibition/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/category` | `/category`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exhibitionLog` | `/exhibitionLog`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mypage` | `/mypage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/liked` | `/mypage/exhibition/liked`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/thumbs-up` | `/mypage/exhibition/thumbs-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/visited` | `/mypage/exhibition/visited`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/category`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/interest`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/exhibition/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/category${`?${string}` | `#${string}` | ''}` | `/category${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exhibitionLog${`?${string}` | `#${string}` | ''}` | `/exhibitionLog${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mypage${`?${string}` | `#${string}` | ''}` | `/mypage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mypage/exhibition/liked${`?${string}` | `#${string}` | ''}` | `/mypage/exhibition/liked${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mypage/exhibition/thumbs-up${`?${string}` | `#${string}` | ''}` | `/mypage/exhibition/thumbs-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mypage/exhibition/visited${`?${string}` | `#${string}` | ''}` | `/mypage/exhibition/visited${`?${string}` | `#${string}` | ''}` | `/onboarding/category${`?${string}` | `#${string}` | ''}` | `/onboarding/interest${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/category` | `/category`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exhibitionLog` | `/exhibitionLog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage` | `/mypage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/liked` | `/mypage/exhibition/liked`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/thumbs-up` | `/mypage/exhibition/thumbs-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage/exhibition/visited` | `/mypage/exhibition/visited`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/category`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/interest`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/exhibition/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/exhibition/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
